seed: &seed 185

# Data Setting
data_folder:  ./data
output_folder:  ./output/

train_batch_size : &train_batch_size 16
valid_batch_size : &valid_batch_size 16
test_batch_size : &test_batch_size 16

train_csv:  train-clean-100.csv
valid_csv:  dev-clean.csv
test_csv:  test-clean.csv

train_loader_kwargs:
    batch_size: *train_batch_size
    shuffle: True,
    num_workers: 6

valid_loader_kwargs:
    batch_size: *valid_batch_size
    shuffle: True,
    num_workers: 6

test_loader_kwargs:
    batch_size: *test_batch_size
    shuffle: True,
    num_workers: 6


number_of_epochs: 5
lr: 0.0001
print_every: 10
# Model Parameters
rnn_type: &rnn_type gru
num_layers: &num_layers 2
hidden_size: &hidden_size 128
embedding_size: &embedding_size 768 #should macch the embedding model
latent_size: &latent_size 64
dropout: &dropout  0.1
embedding_model_name: bert-base-uncased

vocab_size : &vocab_size 30522 #should macch the embedding model
tie_embeddings: &tie_embeddings True
word_dropout: &word_dropout 0.1
embedding_dropout: &embedding_dropout 0.1
max_sequence_length: &max_sequence_length 10

encoder:
    bidirectional: False
    rnn_type : *rnn_type
    num_layers: *num_layers
    dropout: *dropout
    hidden_size: *hidden_size
    embedding_size: *embedding_size
    latent_size: *latent_size

                
decoder:
    bidirectional: False
    rnn_type : *rnn_type
    num_layers: *num_layers
    dropout: *dropout
    hidden_size: *hidden_size
    embedding_size: *embedding_size
    latent_size: *latent_size
    tie_embeddings: *tie_embeddings
    vocab_size: *vocab_size
    word_dropout: *word_dropout
    embedding_dropout: *embedding_dropout
    max_sequence_length: *max_sequence_length







